### ISSUE TITLE
Is OS installation ID a constant per machine?

### ISSUE THREAD

**Issue by techtim** [MatthewKing/DeviceId#23]
Is it stays same when u install newer or reinstall same version of Windows/Linux on the same machine?
Asking because on OSX it is constant through the device lifetime

**Comment by MatthewKing** [comment]
No, it's not necessarily a constant on Windows or Linux.

**Comment by techtim** [comment]
But on OSX it is constant for a particular macbook/macrpo, for example here is mine and it will be same no matter what version of OSX I have: https://checkcoverage.apple.com/gb/en/?sn=C02LN0QVFH04
So the point is that IOPlatformSerialNumber suits more like the CPU ID on OSX.

**Comment by MatthewKing** [comment]
Thanks for the feedback. I'm not a Mac user and the documentation was pretty sparse so it's hard to find this info. I'll look into changing the DeviceID components to better support this. Cheers!
