### ISSUE TITLE
Dockersupport 

### ISSUE THREAD

**Issue by AlexSchuetz** [MatthewKing/DeviceId#26]
If the application runs in a docker container some functions won't work:

- `AddMotherboardSerialNumber()` aka`/sys/class/dmi/id/board_serial` won't work as the file doesn't exit
- `AddSystemUUID()` aka `/sys/class/dmi/id/product_uuid` won't work as the file doesn't exit

Maybe: `head -1 /proc/self/cgroup|cut -d/ -f3` could help out with one of them.

**Comment by MatthewKing** [comment]
Hi Alex. Thanks for this report. It's a bit out of my wheelhouse but hopefully a contributor with linux & docker expertise can sort a PR. Otherwise I'll have a crack at it for the next major version at some point.
