### ISSUE TITLE
System.PlatformNotSupportedException on Win Server 2012

### ISSUE THREAD

**Issue by jarenduan** [MatthewKing/DeviceId#29]
Hi, I write a .net5 app that try to get the machine id. The code is simple:

 ```
public string GetId() => new DeviceIdBuilder()
                                 .AddProcessorId()
                                 .AddMacAddress(true, true)
                                 .ToString();
```

It works fine on win 10, but on a win server 2012 I get this error: `System.PlatformNotSupportedException: The native library 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\wminet_utils.dll' does not have all required functions. Please, update the .NET Framework.`

I then install the .net framework 4.8 , but it doesn't help.

**Comment by MatthewKing** [comment]
I'm not really familiar with Server 2012 but it looks like it is missing some of the required WMI bits.

You could try targeting .NET Core / .NET 5.

Or you could try [the MMI functionality in the v6 alpha release](https://www.nuget.org/packages/DeviceId.Windows.Mmi):
```csharp
var deviceId = new DeviceIdBuilder()
    .OnWindows(windows => windows.AddProcessorId().AddMacAddressFromMmi(true, true))
    .ToString();
```
