### ISSUE TITLE
AddOSInstallationID

### ISSUE THREAD

**Issue by ekaraman89** [MatthewKing/DeviceId#30]
Hello
Returning different values for "AddOSInstallationID" method net5 and framework 4.7.2

**Comment by MatthewKing** [comment]
Can't reproduce this. It's just reading from the registry.

May be an issue with 32bit vs 64bit registry views, but couldn't say without seeing your app.

The improved registry components in [the new version](https://www.nuget.org/packages/DeviceId.Windows) may fix this for you, though.
