### ISSUE TITLE
.AddProcessorId() disappeared in version 6

### ISSUE THREAD

**Issue by Gerardo-Sista** [MatthewKing/DeviceId#39]
Hello,
I have some apps using your lib. 
None works after upgrading to version 6 because .AddProcessorId() simply is no more present.

Can you fix it or tell me how to achieve the equivalent result? 

Thank you.

**Comment by MatthewKing** [comment]
Hi.

You need to add the `DeviceId.Windows.Wmi` package (or the `DeviceId.Windows.Mmi` package).

Refer to the example from the readme:

```csharp
string deviceId = new DeviceIdBuilder()
    .AddMachineName()
    .AddOSVersion()
    .OnWindows(windows => windows
        .AddProcessorId()
        .AddMotherboardSerialNumber()
        .AddSystemSerialDriveNumber())
    .ToString();
```

**Comment by AlexSchuetz** [comment]
I made a little PR with informations how to migrate from 5.x to 6.x

[PR 44](https://github.com/MatthewKing/DeviceId/pull/44)
