### ISSUE TITLE
Referenced assembly 'DeviceId' does not have a strong name

### ISSUE THREAD

**Issue by viktorfilim** [MatthewKing/DeviceId#5]
`Referenced assembly 'DeviceId' does not have a strong name`

Can you sign the package so it can be used in a project where all the assemblies are signed?

**Comment by mylemans** [comment]
https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/

You can always sign it yourself, potentially running in the stated issue. Imho it is a bit pointless these days.

See the answer @ https://stackoverflow.com/questions/331520/how-to-fix-referenced-assembly-does-not-have-a-strong-name-error for that

**Comment by viktorfilim** [comment]
I know i can sign it myself. but after every update i need to resign it. It would be a lot better if the package came already signed.
And i know it is pointless. But the app is old and the client wants it signed. So what ca we do?

**Comment by viktorfilim** [comment]
Also => https://www.pedrolamas.com/2018/09/11/start-strong-naming-your-assemblies/

**Comment by mylemans** [comment]
Well be sure to read up on this too: https://github.com/dotnet/runtime/blob/master/docs/project/strong-name-signing.md :P

It is stated there public libraries should sign, but then followed by a list with the potential issues.

I'm not saying they shouldn't release a signed version, take note that I did point you to a solution that you could do yourself now if the non signed thing was a blocking issue for you :)

**Comment by MatthewKing** [comment]
Hey folks. Thanks for the discussion.

I've been a bit conflicted about strong naming this library in the past. Generally I'm against strong naming, but obviously this library gets used in a lot of enterprise software environments where strong naming is used, and so strong naming this library would help developers who are using it in that context. As a result, I'm open to the idea.

I've got some plans for a new major version release with a couple of changes to the public API and a few new features. I'll consider strong naming that next release. And hopefully the technique linked by @mylemans is enough for everyone using the existing versions.

**Comment by Welchen** [comment]
Any chance of this strong naming happening?

**Comment by MatthewKing** [comment]
I've got a new release planned in the next few days. I will probably bite the bullet and strong name it.
