### ISSUE TITLE
Version compatible

### ISSUE THREAD

**Issue by Luigi6821** [MatthewKing/DeviceId#50]
Hi,
I am using version 5.2 for generating DeviceID as follows:
string deviceId = new DeviceIdBuilder()
                                .AddMachineName()
                                .AddProcessorId()
                                .AddMotherboardSerialNumber()
                                .ToString();

I noted that on version 6.2 the "same" instructions generate a different result:
string deviceId = new DeviceIdBuilder()
                                .AddMachineName()
                                .OnWindows(windows => windows.AddProcessorId().AddMotherboardSerialNumber())
                                .ToString();

Is possible to generated a device ID which is back-compatible with version 5.2?

Thanks in advance
Luigi

**Comment by MatthewKing** [comment]
The default formatter changed between V5 and V6.
Try adding `.UseFormatter(DeviceIdFormatters.DefaultV5)`

**Comment by Luigi6821** [comment]
> .UseFormatter(DeviceIdFormatters.DefaultV5)

Thank you Matthew it solved.

Regards
Luigi
