### ISSUE TITLE
Convert String to Component

### ISSUE THREAD

**Issue by krulci** [MatthewKing/DeviceId#57]
After creating a deviceId, how do you convert it back if you know the conponents of builder?
I am trying to create a client and server communication.

**Comment by MatthewKing** [comment]
This depends on which implementation of `IDeviceIdFormatter` and `IDeviceIdComponentEncoder` that you use.

Out of the box, it's a one-way process and you can't go back. Think of it like a hash.

But you could implement your own reversible version if you want - just implement `IDeviceIdFormatter` and pass it to your builder with the `.UseFormatter` method.
