### ISSUE TITLE
[Question] DeviceId 6.3 nuget release dates?

### ISSUE THREAD

**Issue by rmszc81** [MatthewKing/DeviceId#61]
Good afternoon @MatthewKing,
Is there any date for releasing the new version as a nuget package? It's still not available, only 6.2.
Thank you.

**Comment by MatthewKing** [comment]
The relevant changes were in [DeviceId.Linux](https://www.nuget.org/packages/DeviceId.Linux), which is on NuGet as 6.3

**Comment by rmszc81** [comment]
Yes, you're right, I didn't pay attention and I'm sorry.
Btw, thank you for the great work!

**Comment by MatthewKing** [comment]
All good mate. And thanks for the positive feedback. Cheers
