### ISSUE TITLE
Device ID on docker container

### ISSUE THREAD

**Issue by Luigi6821** [MatthewKing/DeviceId#66]
Hi,
I have a question about docker container in particular running on azure.
I am using DeviceId library to have a unque ID for generating license for customer that want to use our company software.
I experienced that on any container creation (and it is also correct) the DeviceID changes and therefore license become invalid.
When running docker hosted in azure could be useful to get the Azure tenantId of the current running subscription.
In general I would like to have a unique ID when running docker even after having built a new container.

Any suggestion?
Thanks in advance

**Comment by MatthewKing** [comment]
Yes, you can implement your own custom `IDeviceIdComponent` to use whatever info the app can access. There are no Azure-specific components out-of-the-box, though, so you will have to implement your own.

**Comment by Luigi6821** [comment]
> Yes, you can implement your own custom `IDeviceIdComponent` to use whatever info the app can access. There are no Azure-specific components out-of-the-box, though, so you will have to implement your own.

 I thought there was something already or in development..
Thanks anyway

**Comment by greendimka** [comment]
@Luigi6821, probably this issue can be closed.

**Comment by Luigi6821** [comment]
Yes thanks.
