### ISSUE TITLE
Using package DeviceId.Wmi - MotherboardSerialNumber gives WPF scroll issues

### ISSUE THREAD

**Issue by PepijnHogervorst** [MatthewKing/DeviceId#77]
For a full stack WPF application with multiple projects the `DeviceId.Wmi` library for some reason gives touch scroll issues when used. 

Adding the library as Nuget package to my Infrastructure layer project would make my WPF UI layer project give touch scroll issues. The touch still works but the scrollviewer in particular could not easily be scrolled anymore *(`PanningMode` is set to `Both`)*. 

I have created a simple project where the issue is active: [TestTouchScroll-issue.zip](https://github.com/MatthewKing/DeviceId/files/13187886/TestTouchScroll-issue.zip). If you comment the lines in the `MainWindow.xaml.cs` - line 15 to 18 the problem is fixed. So it has to do something with the `.AddMotherboardSerialNumber()`  or `.AddMachineGuid()` method that is called. I also found out that removing the MotherboardSerialNumber method fixes the issue. (the MachineGuid method doesn't use the Wmi library, i suspect the problem to lie in the Wmi library).

Hopefully this information is useful enough and feel free to ask for more information if required! Thank you in advance! Great library never the less!

Cheers, Pepijn

**Comment by MatthewKing** [comment]
That's a very strange one!

Doing a bit of research, I see the following similar issues:
* https://github.com/dotnet/runtime/issues/522
* https://github.com/dotnet/wpf/issues/2393

I notice a workaround is posted in those issues. Does using that workaround help for your case?

Cheers

**Comment by PepijnHogervorst** [comment]
Thank you for the quick response. The workaround *(adding `_ = Tablet.TabletDevices;` to the )* does work for the `TestTouchScroll` project but unfortunately not for the full stack application I am working on. The startup there is more complex (using async). For now I will not use the MotherboardSerialNumber anymore to work around this issue!
