### ISSUE TITLE
Needed Signed Version of DeviceID Assemblies

### ISSUE THREAD

**Issue by sudhakar269** [MatthewKing/DeviceId#78]
I need the digitally signed version of assemblies as part of the DeviceID nuget package ,Is there any way to get that ???

**Comment by MatthewKing** [comment]
The assemblies are strong named but not signed.

I haven't seen a compelling reason to sign them thus far, but I'm willing to consider it if given a good enough reason.

Why do you need this? And why not sign them yourself?

Cheers

**Comment by BobbyCannon** [comment]
Yeah, I thought the same thing with my open-source project. It's not possible if you have any dependencies that are not signed. Hence the commenters issue. It is very simple to generate a onetime snk file then sign the assembly during build.

This simple step removes one more barrier for your users that just makes life a bit easier. Being that it's so easy I always sign my open-source assemblies so it's just easier for everyone.

All you have to do is generate the SNK then add three lines for your project files or Directory.Build.props file.

<SignAssembly>false</SignAssembly>
<DelaySign>false</DelaySign>
<AssemblyOriginatorKeyFile>Cornerstone.snk</AssemblyOriginatorKeyFile>

I've never actually contributed to another open-source project. If you'd be open to the idea, then I'll go do the work for it and submit it.

**Comment by BobbyCannon** [comment]
Ok, I forked then started working on this just to help and realized the assemblies are already being signed... So I just deleted the fork. 

The assemblies appear to already be signed.
