### ISSUE TITLE
AddWindowsDeviceId() and AddWindowsProductId() in 32 bit processes

### ISSUE THREAD

**Issue by IsThatUniqueEnough** [MatthewKing/DeviceId#79]
Components created with `AddWindowsDeviceId()` and `AddWindowsProductId()` return `null` when run in 32 bit processes (target "x86" or "Any CPU") on 64 bit Windows:

``` C#
var builder = new DeviceIdBuilder()
    .OnWindows(windows => windows
    .AddWindowsDeviceId()
    .AddWindowsProductId());

foreach (var component in builder.Components)
    Console.WriteLine($"{component.Key}: {component.Value.GetValue() ?? "null"}");
```

gives:

```
WindowsDeviceId: null
WindowsProductId: null
```

Expected behaviour: Return the requested ids.

**Comment by MatthewKing** [comment]
Thanks for the report. This will be fixed in the next minor release over the next couple of days.
