### ISSUE TITLE
Connection string property vanishes  , @DeviceId.SqlServer

### ISSUE THREAD

**Issue by SreeVardhanTulluri** [MatthewKing/DeviceId#88]
I'm utilizing DeviceId to identify logs within my application. Initially, I successfully created a machine ID and other components using DeviceId.Windows. Later, I attempted to enhance this by incorporating the database connection ID whenever a user opens and subsequently closes a connection. However, when I call the function to retrieve the SqlConnectionId using the connection variable of type SqlConnection, its ConnectionString property is unexpectedly becoming null or empty."

<img width="382" alt="Screenshot 2024-07-05 182152" src="https://github.com/MatthewKing/DeviceId/assets/170911250/8df77a6f-69d0-4517-933b-2435dbf6b3fe">

**Comment by SreeVardhanTulluri** [comment]
Before calling above function
![image](https://github.com/MatthewKing/DeviceId/assets/170911250/68fbb2a3-7752-4900-93ea-c4ea86a0bb17)
after calling above function
![image](https://github.com/MatthewKing/DeviceId/assets/170911250/0d776701-85e6-4335-8c5d-8cb47537753a)

**Comment by MatthewKing** [comment]
Thanks for the bug report. This should be fixed in 6.7.0, have a try and let me know how it goes. Cheers

**Comment by iris-jen** [comment]
I'm having the same issue with 6.7.0

Here the connection string is fine
![image](https://github.com/user-attachments/assets/d3647aab-a455-4a8a-bcd5-630b67159df9)

Then after the SQL connection call, the connection string disappears and the connection closes
![image](https://github.com/user-attachments/assets/7745eef2-3654-4032-a8a5-23639ebb91f4)

All Ids produced are the same as the result from the windows calls, 
I'm assuming it returns a GUID when the platform is incorrect.
Im running this code in a docker container, so i would not expect the windows id's to be valid, but the SQL ones seem the same too

 sqlDbId                          WERC8GMRZGE196QVYK49JVXS4GKTWGF4CJDS6K54JPCHPY2JQ1AG 
 sqlServerName              WERC8GMRZGE196QVYK49JVXS4GKTWGF4CJDS6K54JPCHPY2JQ1AG 
 sqlDbName                   WERC8GMRZGE196QVYK49JVXS4GKTWGF4CJDS6K54JPCHPY2JQ1AG 

 winProdId                      WERC8GMRZGE196QVYK49JVXS4GKTWGF4CJDS6K54JPCHPY2JQ1AG 
 winProcId                       WERC8GMRZGE196QVYK49JVXS4GKTWGF4CJDS6K54JPCHPY2JQ1AG 
 winMac                          WERC8GMRZGE196QVYK49JVXS4GKTWGF4CJDS6K54JPCHPY2JQ1AG 
 winSys                            WERC8GMRZGE196QVYK49JVXS4GKTWGF4CJDS6K54JPCHPY2JQ1AG 
 winMachineGuid            WERC8GMRZGE196QVYK49JVXS4GKTWGF4CJDS6K54JPCHPY2JQ1AG 
 winSysDriveSn                WERC8GMRZGE196QVYK49JVXS4GKTWGF4CJDS6K54JPCHPY2JQ1AG 
 
 linuxProcId                     XW9EVPW00FXHKMCVVGB0EDGPX8TEYF4KT4YWR8KDPQ4DJ7PP3AX0 
 containerId                     W3RCVFNZTEWXST1KRQ8K737TK87H2EKYXW0R9FYN6XPR0T8QCVH0 


Using the following versions
![image](https://github.com/user-attachments/assets/b76cc8d4-0d2e-40b7-9aa9-1ca7f717dfda)

**Comment by MatthewKing** [comment]
Hi, thanks for the report. Fixed in 6.7.1.
