### ISSUE TITLE
Problematic dependecy in DeviceId.Linux

### ISSUE THREAD

**Issue by Zyklop** [MatthewKing/DeviceId#92]
The package DeviceId.Linux contains a dependency to System.Text.Json 7.0.0 which has a high severity vulnerability.

9.0.0 or 8.0.5 should be fine

**Comment by Zyklop** [comment]
I just noticed there is already a PR for it: #89

**Comment by MatthewKing** [comment]
Thanks. I've fixed this in the recent commits, and will be pushing a new version to NuGet soon.
