### ISSUE TITLE
knowledge of which IDs are actually hardware based.

### ISSUE THREAD

**Issue by vpenades** [MatthewKing/DeviceId#93]
I've been tasked to generate an ID based on hardware IDs, so it returns a different ID even if the sofware is closed using a full image of the whole disk and copied to another machine.

I've realized that several IDs are actually generated by the drivers, which means they're copied around along the disk image, so they're the same when executed in multiple cloned machines.

Is there a chart, or some knowledge base that tells which IDs can be safely used to actually distinguish two hardwares apart, and which IDs may be copied around along disk images?

I am aware this is a non trivial question and answers can vary between vendors.

**Comment by MatthewKing** [comment]
In this situation, it's probably the MAC address.

The main four "100% hardware" values that DeviceID uses are MAC address, processor ID, motherboard serial, and system drive serial. Unfortunately, the latter three are not always reliable as it depends on the vendor (and drivers) actually reporting the aforementioned values: many vendors unfortunately just report default/empty values for some of these.

**Comment by vpenades** [comment]
Thanks, sadly that's the answer I guessed.

In any case it could be useful to have additional information on every Id, things that come to mind:
- Scope (per machine/per user/per application)
- Hardware backed.
- Reliability/robustness.
